[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_minting = "5GazsE1oEPBpPWSc7UFAyNr2LfTSpBKQ8AX7was68VqY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/Abhi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
